import type { AlbumMedia, Book, BookExcerpt, BirthdayNotificationSchedule, CheckIn, DayKey, Draft, Media, MusicCollectionEntry, MusicTrack, Person, PersonAlbum, PersonTagAssignment, Post, ProfileCollectionRequest, ReadingNoteSource, TagDefinition, TagSystemSetting } from '@still-alive/types';

export interface StillAliveRepository {
  checkIn(dayKey: DayKey): Promise<CheckIn>;
  updateCheckInCity(checkInId: string, city: string): Promise<void>;
  getCheckIn(dayKey: DayKey): Promise<CheckIn | null>;
  listCheckIns(): Promise<CheckIn[]>;
  createPost(post: Post, personIds?: string[]): Promise<void>;
  updatePost(post: Post, personIds?: string[]): Promise<void>;
  deletePost(postId: string): Promise<void>;
  listPersonIdsByPost(postId: string): Promise<string[]>;
  listPosts(): Promise<Post[]>;
  listPostsByDay(dayKey: DayKey): Promise<Post[]>;
  listPostsByPerson(personId: string): Promise<Post[]>;
  saveDraft(draft: Draft): Promise<void>;
  getDraft(dayKey: DayKey): Promise<Draft | null>;
  listMedia(): Promise<Media[]>;
  createMedia(media: Media): Promise<void>;
  updateMedia(media: Media): Promise<void>;
  deleteMedia(mediaId: string): Promise<void>;
  isMediaReferenced(mediaId: string): Promise<boolean>;
  listPeople(): Promise<Person[]>;
  createPerson(person: Person): Promise<void>;
  updatePerson(person: Person): Promise<void>;
  deletePerson(personId: string): Promise<void>;
  setPersonMemoryEnabled(personId: string, enabled: boolean): Promise<void>;
  listTagDefinitions(): Promise<TagDefinition[]>;
  createTagDefinition(tag: TagDefinition): Promise<void>;
  updateTagDefinition(tag: TagDefinition): Promise<void>;
  deleteTagDefinition(tagId: string): Promise<void>;
  countPeopleByTag(tagId: string): Promise<number>;
  listTagSystemSettings(): Promise<TagSystemSetting[]>;
  updateTagSystemSettings(settings: TagSystemSetting[]): Promise<void>;
  listPersonTagAssignments(): Promise<PersonTagAssignment[]>;
  setPersonTags(personId: string, mbti: string | null, customTagIds: string[]): Promise<void>;
  listAlbums(): Promise<PersonAlbum[]>;
  createAlbum(album: PersonAlbum): Promise<void>;
  updateAlbum(album: PersonAlbum): Promise<void>;
  deleteAlbum(albumId: string): Promise<void>;
  listAlbumMedia(): Promise<AlbumMedia[]>;
  addAlbumMedia(item: AlbumMedia, media: Media): Promise<void>;
  updateAlbumMedia(albumId: string, items: AlbumMedia[]): Promise<void>;
  removeAlbumMedia(albumId: string, mediaId: string): Promise<void>;
  listBirthdayNotificationSchedules(): Promise<BirthdayNotificationSchedule[]>;
  replaceBirthdayNotificationSchedules(items: BirthdayNotificationSchedule[]): Promise<void>;
  createProfileCollectionRequest(request: ProfileCollectionRequest): Promise<void>;
  getProfileCollectionRequest(requestId: string): Promise<ProfileCollectionRequest | null>;
  listProfileCollectionRequestIds(): Promise<string[]>;
  consumeProfileCollectionRequest(requestId: string, consumedAt: string): Promise<void>;
  deleteProfileCollectionRequest(requestId: string): Promise<void>;
  deleteExpiredProfileCollectionRequests(now: string): Promise<string[]>;
  applyProfileCollectionUpdate(requestId: string, person: Person, mbti: string | null, customTagIds: string[], newTags: TagDefinition[], consumedAt: string): Promise<void>;
  listMusicTracks(): Promise<MusicTrack[]>;
  createMusicTrack(track: MusicTrack, collection?: MusicCollectionEntry): Promise<void>;
  updateMusicTrack(track: MusicTrack): Promise<void>;
  deleteMusicTrack(trackId: string): Promise<void>;
  listMusicCollectionEntries(): Promise<MusicCollectionEntry[]>;
  addMusicCollectionEntry(entry: MusicCollectionEntry): Promise<void>;
  removeMusicCollectionEntry(trackId: string, targetType: MusicCollectionEntry['targetType'], targetId: string | null): Promise<void>;
  listBooks(): Promise<Book[]>;
  createBook(book: Book): Promise<void>;
  updateBook(book: Book): Promise<void>;
  deleteBook(bookId: string): Promise<void>;
  listBookExcerpts(bookId?: string): Promise<BookExcerpt[]>;
  createBookExcerpt(excerpt: BookExcerpt): Promise<void>;
  updateBookExcerpt(excerpt: BookExcerpt): Promise<void>;
  deleteBookExcerpt(excerptId: string): Promise<void>;
  getReadingNoteSource(postId: string): Promise<ReadingNoteSource | null>;
  saveReadingNoteSource(source: ReadingNoteSource): Promise<void>;
}
