import type { AlbumMedia, Book, BookExcerpt, BookList, BookListEntry, CheckIn, DayKey, Draft, Media, MusicCollectionEntry, MusicPlaylist, MusicPlaylistEntry, MusicTrack, Person, PersonAlbum, PersonBook, PersonRelationship, PersonRelationshipKind, PersonRelationshipNode, PersonTagAssignment, Post, ProfileCollectionRequest, ReadingNoteSource, TagDefinition, TagGroup, TagSystemSetting } from '@still-alive/types';
import type { AppPreferences, BackupSnapshot, HomeMemory } from '../../infrastructure/database/database-models';

export interface AppStateValue {
  today: DayKey;
  todayCheckIn: CheckIn | null;
  checkIns: CheckIn[];
  posts: Post[];
  people: Person[];
  personRelationships: PersonRelationship[];
  personRelationshipNodes: PersonRelationshipNode[];
  media: Media[];
  tagDefinitions: TagDefinition[];
  tagGroups: TagGroup[];
  tagSystemSettings: TagSystemSetting[];
  personTags: PersonTagAssignment[];
  albums: PersonAlbum[];
  albumMedia: AlbumMedia[];
  personBooks: PersonBook[];
  musicTracks: MusicTrack[];
  musicCollectionEntries: MusicCollectionEntry[];
  musicPlaylists: MusicPlaylist[];
  musicPlaylistEntries: MusicPlaylistEntry[];
  bookLists: BookList[];
  bookListEntries: BookListEntry[];
  books: Book[];
  bookExcerpts: BookExcerpt[];
  readingNoteSources: ReadingNoteSource[];
  homeMemory: HomeMemory | null;
  preferences: AppPreferences;
  notificationPermission: 'granted' | 'denied' | 'undetermined';
  persistentNotificationRunning: boolean;
  persistentNotificationSupported: boolean;
  shouldShowBackupReminder: boolean;
  ready: boolean;
  error: string | null;
  checkInToday(): Promise<CheckIn>;
  updateCheckInCity(checkInId: string, city: string): Promise<void>;
  savePost(bodyMarkdown: string, personIds?: string[], dayKey?: DayKey, locationName?: string | null): Promise<Post>;
  updatePost(postId: string, bodyMarkdown: string, personIds?: string[], locationName?: string | null): Promise<void>;
  deletePost(postId: string): Promise<void>;
  getPersonIdsByPost(postId: string): Promise<string[]>;
  getPostsByPerson(personId: string): Promise<Post[]>;
  saveMedia(item: Media): Promise<void>;
  replaceMedia(mediaId: string, replacement: Media): Promise<void>;
  discardMedia(media: Media): Promise<void>;
  createPerson(name: string): Promise<Person>;
  updatePerson(personId: string, changes: Pick<Person, 'name' | 'nickname' | 'bio' | 'avatarMediaId' | 'gender' | 'relationToMe' | 'impression' | 'birthday'>, mbti?: string | null, customTagIds?: string[]): Promise<void>;
  deletePerson(personId: string): Promise<void>;
  createPersonRelationshipNode(personId?: string | null, label?: string | null): Promise<PersonRelationshipNode>;
  deletePersonRelationshipNode(nodeId: string): Promise<void>;
  bindPersonRelationshipNode(nodeId: string, personId: string | null): Promise<void>;
  savePersonRelationship(sourceNodeId: string, targetNodeId: string, kind: PersonRelationshipKind, relationshipId?: string | null): Promise<PersonRelationship>;
  deletePersonRelationship(relationshipId: string): Promise<void>;
  setPersonMemoryEnabled(personId: string, enabled: boolean): Promise<void>;
  setPersonBooks(personId: string, bookIds: string[]): Promise<void>;
  createTag(name: string, groupId?: string | null): Promise<TagDefinition>;
  renameTag(tagId: string, name: string): Promise<void>;
  deleteTag(tagId: string): Promise<void>;
  createTagGroup(name: string): Promise<TagGroup>;
  renameTagGroup(groupId: string, name: string): Promise<void>;
  deleteTagGroup(groupId: string): Promise<void>;
  countPeopleByTag(tagId: string): Promise<number>;
  updateTagSystems(settings: TagSystemSetting[]): Promise<void>;
  createAlbum(personId: string | null, name: string): Promise<PersonAlbum>;
  updateAlbum(albumId: string, changes: Partial<Pick<PersonAlbum, 'name' | 'coverMediaId' | 'sortOrder'>>): Promise<void>;
  deleteAlbum(albumId: string): Promise<void>;
  addPhotoToAlbum(albumId: string, item: Media): Promise<void>;
  reorderAlbumPhotos(albumId: string, orderedMediaIds: string[]): Promise<void>;
  removePhotoFromAlbum(albumId: string, mediaId: string): Promise<void>;
  saveDraft(bodyMarkdown: string, dayKey?: DayKey): Promise<void>;
  loadDraft(dayKey?: DayKey): Promise<Draft | null>;
  createBackupSnapshot(): Promise<BackupSnapshot>;
  restoreBackupSnapshot(snapshot: BackupSnapshot): Promise<void>;
  updatePreferences(changes: Partial<AppPreferences>): Promise<void>;
  setBirthdayNotificationsEnabled(enabled: boolean): Promise<void>;
  retryBirthdayNotifications(): Promise<void>;
  setMemoryNotificationsEnabled(enabled: boolean): Promise<void>;
  retryMemoryNotifications(): Promise<void>;
  setPersistentNotificationsEnabled(enabled: boolean): Promise<void>;
  openNotificationSettings(): Promise<void>;
  recordBackupExport(): Promise<void>;
  dismissBackupReminder(): Promise<void>;
  deleteAllLocalData(): Promise<void>;
  createProfileCollectionRequest(request: ProfileCollectionRequest, privateKeyJwk: string): Promise<void>;
  getProfileCollectionRequest(requestId: string): Promise<ProfileCollectionRequest | null>;
  deleteProfileCollectionRequest(requestId: string): Promise<void>;
  applyProfileCollectionImport(requestId: string, person: Person, mbti: string | null, customTagIds: string[], newTagNames: string[]): Promise<void>;
  importMusicTrack(item: Media, personId?: string | null): Promise<MusicTrack>;
  createMusicTrack(track: MusicTrack, collection?: MusicCollectionEntry): Promise<void>;
  updateMusicTrack(track: MusicTrack, cover?: Media | null): Promise<void>;
  incrementMusicTrackPlayCount(trackId: string): Promise<void>;
  setMusicTrackCover(trackId: string, cover: Media | null): Promise<void>;
  deleteMusicTrack(trackId: string): Promise<void>;
  addMusicCollectionEntry(entry: MusicCollectionEntry): Promise<void>;
  removeMusicCollectionEntry(trackId: string, targetType: MusicCollectionEntry['targetType'], targetId: string | null): Promise<void>;
  createMusicPlaylist(name: string): Promise<MusicPlaylist>;
  renameMusicPlaylist(playlistId: string, name: string): Promise<void>;
  setMusicPlaylistCover(playlistId: string, cover: Media | null): Promise<void>;
  deleteMusicPlaylist(playlistId: string): Promise<void>;
  addMusicTracksToPlaylist(playlistId: string, trackIds: string[]): Promise<void>;
  removeMusicTrackFromPlaylist(playlistId: string, trackId: string): Promise<void>;
  createBookList(name: string): Promise<BookList>;
  renameBookList(listId: string, name: string): Promise<void>;
  deleteBookList(listId: string): Promise<void>;
  addBooksToList(listId: string, bookIds: string[]): Promise<void>;
  removeBookFromList(listId: string, bookId: string): Promise<void>;
  createBook(book: Book): Promise<void>;
  updateBook(book: Book): Promise<void>;
  deleteBook(bookId: string): Promise<void>;
  createBookExcerpt(excerpt: BookExcerpt): Promise<void>;
  updateBookExcerpt(excerpt: BookExcerpt): Promise<void>;
  deleteBookExcerpt(excerptId: string): Promise<void>;
  getReadingNoteSource(postId: string): Promise<ReadingNoteSource | null>;
  saveReadingNoteSource(source: ReadingNoteSource): Promise<void>;
  deleteReadingNoteSource(postId: string): Promise<void>;
}
