import type { AppPreferences } from '../../infrastructure/database/database-models';

export const DEFAULT_PREFERENCES: AppPreferences = {
  onboardingCompleted: false,
  nickname: '',
  profileBio: '',
  profileSignature: '',
  profileGender: null,
  appearanceTheme: 'moss',
  selfNameStyle: 'fresh',
  friendNameStyle: 'journal',
  birthDate: '',
  birthDateCalendar: 'solar',
  birthDateIsLeapMonth: false,
  profileAvatarMediaId: null,
  profileMbti: '',
  profileCustomTagIds: [],
  globalMemoryEnabled: true,
  lastExportAt: null,
  lastExportPostCount: 0,
  backupReminderShownAt: null,
  birthdayNotificationsEnabled: false,
  birthdayReminderHour: 9,
  birthdayReminderMinute: 0,
  birthdayNotificationError: null,
  memoryNotificationsEnabled: false,
  memoryNotificationError: null,
  persistentNotificationEnabled: false,
  musicPlaybackMode: 'list',
  miniPlayerX: 0,
  miniPlayerY: 0,
  miniPlayerEdge: null,
  miniPlayerYRatio: null,
  readerPreferencesJson: '{}',
};
