import type { AlbumMedia, Book, BookExcerpt, BookList, BookListEntry, BirthdayNotificationSchedule, CheckIn, DayKey, Draft, Media, MusicCollectionEntry, MusicPlaylist, MusicPlaylistEntry, MusicTrack, Person, PersonAlbum, PersonBook, PersonEvent, PersonRelationship, PersonRelationshipNode, PersonTagAssignment, Post, ProfileCollectionRequest, ReadingNoteSource, TagDefinition, TagSystemSetting } from '@still-alive/types';

export interface StillAliveRepository {
  checkIn(dayKey: DayKey): Promise<CheckIn>;
  updateCheckInCity(checkInId: string, city: string): Promise<void>;
  getCheckIn(dayKey: DayKey): Promise<CheckIn | null>;
  listCheckIns(): Promise<CheckIn[]>;
  createPost(post: Post, personIds?: string[]): Promise<void>;
  updatePost(post: Post, personIds?: string[]): Promise<void>;
  deletePost(postId: string): Promise<void>;
  listPersonIdsByPost(postId: string): Promise<string[]>;
  listPosts(): Promise<Post[]>;
  listPostsByDay(dayKey: DayKey): Promise<Post[]>;
  listPostsByPerson(personId: string): Promise<Post[]>;
  saveDraft(draft: Draft): Promise<void>;
  getDraft(dayKey: DayKey): Promise<Draft | null>;
  listMedia(): Promise<Media[]>;
  createMedia(media: Media): Promise<void>;
  updateMedia(media: Media): Promise<void>;
  deleteMedia(mediaId: string): Promise<void>;
  isMediaReferenced(mediaId: string): Promise<boolean>;
  listPeople(): Promise<Person[]>;
  createPerson(person: Person): Promise<void>;
  updatePerson(person: Person): Promise<void>;
  deletePerson(personId: string): Promise<string[]>;
  listPersonRelationships(): Promise<PersonRelationship[]>;
  listPersonRelationshipNodes(): Promise<PersonRelationshipNode[]>;
  savePersonRelationshipNode(node: PersonRelationshipNode): Promise<void>;
  deletePersonRelationshipNode(nodeId: string): Promise<void>;
  savePersonRelationship(relationship: PersonRelationship): Promise<void>;
  deletePersonRelationship(relationshipId: string): Promise<void>;
  setPersonMemoryEnabled(personId: string, enabled: boolean): Promise<void>;
  listPersonEvents(personId?: string): Promise<PersonEvent[]>;
  savePersonEvent(event: PersonEvent): Promise<void>;
  deletePersonEvent(eventId: string): Promise<void>;
  mergePersons(targetPersonId: string, sourcePersonIds: string[]): Promise<void>;
  listPersonBooks(): Promise<PersonBook[]>;
  setPersonBooks(personId: string, bookIds: string[]): Promise<void>;
  listTagDefinitions(): Promise<TagDefinition[]>;
  createTagDefinition(tag: TagDefinition): Promise<void>;
  updateTagDefinition(tag: TagDefinition): Promise<void>;
  deleteTagDefinition(tagId: string): Promise<void>;
  countPeopleByTag(tagId: string): Promise<number>;
  listTagSystemSettings(): Promise<TagSystemSetting[]>;
  updateTagSystemSettings(settings: TagSystemSetting[]): Promise<void>;
  listPersonTagAssignments(): Promise<PersonTagAssignment[]>;
  setPersonTags(personId: string, mbti: string | null, customTagIds: string[]): Promise<void>;
  listAlbums(): Promise<PersonAlbum[]>;
  createAlbum(album: PersonAlbum): Promise<void>;
  updateAlbum(album: PersonAlbum): Promise<void>;
  deleteAlbum(albumId: string): Promise<void>;
  listAlbumMedia(): Promise<AlbumMedia[]>;
  addAlbumMedia(item: AlbumMedia, media: Media): Promise<void>;
  updateAlbumMedia(albumId: string, items: AlbumMedia[]): Promise<void>;
  removeAlbumMedia(albumId: string, mediaId: string): Promise<void>;
  listBirthdayNotificationSchedules(): Promise<BirthdayNotificationSchedule[]>;
  replaceBirthdayNotificationSchedules(items: BirthdayNotificationSchedule[]): Promise<void>;
  createProfileCollectionRequest(request: ProfileCollectionRequest): Promise<void>;
  getProfileCollectionRequest(requestId: string): Promise<ProfileCollectionRequest | null>;
  listProfileCollectionRequestIds(): Promise<string[]>;
  consumeProfileCollectionRequest(requestId: string, consumedAt: string): Promise<void>;
  deleteProfileCollectionRequest(requestId: string): Promise<void>;
  deleteExpiredProfileCollectionRequests(now: string): Promise<string[]>;
  applyProfileCollectionUpdate(requestId: string, person: Person, mbti: string | null, customTagIds: string[], newTags: TagDefinition[], consumedAt: string): Promise<void>;
  listMusicTracks(): Promise<MusicTrack[]>;
  importMusicTrack(media: Media, track: MusicTrack, collections: MusicCollectionEntry[], coverMedia?: Media | null): Promise<void>;
  attachMusicTrackCover(trackId: string, coverMedia: Media, expectedCoverMediaId?: string | null): Promise<boolean>;
  createMusicTrack(track: MusicTrack, collection?: MusicCollectionEntry): Promise<void>;
  updateMusicTrack(track: MusicTrack): Promise<void>;
  incrementMusicTrackPlayCount(trackId: string): Promise<void>;
  deleteMusicTrack(trackId: string): Promise<void>;
  listMusicCollectionEntries(): Promise<MusicCollectionEntry[]>;
  addMusicCollectionEntry(entry: MusicCollectionEntry): Promise<void>;
  removeMusicCollectionEntry(trackId: string, targetType: MusicCollectionEntry['targetType'], targetId: string | null): Promise<boolean>;
  listMusicPlaylists(): Promise<MusicPlaylist[]>;
  createMusicPlaylist(playlist: MusicPlaylist): Promise<void>;
  updateMusicPlaylist(playlist: MusicPlaylist): Promise<void>;
  deleteMusicPlaylist(playlistId: string): Promise<void>;
  listMusicPlaylistEntries(): Promise<MusicPlaylistEntry[]>;
  addMusicPlaylistEntries(entries: MusicPlaylistEntry[]): Promise<void>;
  removeMusicPlaylistEntry(playlistId: string, trackId: string): Promise<void>;
  listBookLists(): Promise<BookList[]>;
  createBookList(list: BookList): Promise<void>;
  updateBookList(list: BookList): Promise<void>;
  deleteBookList(listId: string): Promise<void>;
  listBookListEntries(): Promise<BookListEntry[]>;
  addBookListEntries(entries: BookListEntry[]): Promise<void>;
  removeBookListEntry(listId: string, bookId: string): Promise<void>;
  listBooks(): Promise<Book[]>;
  createBook(book: Book): Promise<void>;
  updateBook(book: Book): Promise<void>;
  deleteBook(bookId: string): Promise<void>;
  listBookExcerpts(bookId?: string): Promise<BookExcerpt[]>;
  createBookExcerpt(excerpt: BookExcerpt): Promise<void>;
  updateBookExcerpt(excerpt: BookExcerpt): Promise<void>;
  deleteBookExcerpt(excerptId: string): Promise<void>;
  listReadingNoteSources(): Promise<ReadingNoteSource[]>;
  getReadingNoteSource(postId: string): Promise<ReadingNoteSource | null>;
  saveReadingNoteSource(source: ReadingNoteSource): Promise<void>;
  deleteReadingNoteSource(postId: string): Promise<void>;
}
